# Generated by Django 3.0.3 on 2023-06-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoraModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lora_cm_name', models.CharField(help_text='这个自定义', max_length=100, verbose_name='Lora名称')),
                ('lora_cn_name', models.CharField(default='<lora:20d_v10:1>', help_text='你在SD页面选择lora是这样就复制过来这样的内容 <lora:20d_v10:1>', max_length=100, verbose_name='Lora名称')),
            ],
        ),
    ]
