# Generated by Django 3.0.3 on 2023-06-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loramodels',
            name='lora_cm_name',
        ),
    ]
