# Generated by Django 3.0.3 on 2023-06-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_remove_loramodels_lora_cm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loramodels',
            name='lora_en_name',
            field=models.CharField(default='<lora:20d_v10:1>', help_text='你在SD页面选择lora是这样就复制过来这样的内容 <lora:20d_v10:1>', max_length=100, verbose_name='Lora名称'),
        ),
        migrations.AlterField(
            model_name='loramodels',
            name='lora_cn_name',
            field=models.CharField(help_text='这个自定义', max_length=100, verbose_name='Lora名称'),
        ),
    ]
