# Generated by Django 3.0.3 on 2023-06-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0003_auto_20230604_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loramodels',
            options={'verbose_name': 'Lora模型管理', 'verbose_name_plural': 'Lora模型管理'},
        ),
        migrations.AlterField(
            model_name='loramodels',
            name='lora_cn_name',
            field=models.CharField(help_text='Lora的文件名称，确保你是SD/models/Lora中有该文件', max_length=100, verbose_name='Lora名称'),
        ),
    ]
