# Generated by Django 3.0.3 on 2023-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0005_gpt_closeai_gpt_microsoft_gpt_openai_gpt_zsy_tts_microsoft_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loramodels',
            name='lora_cn_name',
            field=models.CharField(help_text='Lora的文件名称，确保你是SD/models/Lora中有该文件', max_length=100, verbose_name='Lora 中文备注'),
        ),
        migrations.AlterField(
            model_name='loramodels',
            name='lora_en_name',
            field=models.CharField(default='<lora:20d_v10:1>', help_text='你在SD页面选择lora是这样就复制过来这样的内容 <lora:20d_v10:1>', max_length=100, verbose_name='Lora SD标签'),
        ),
    ]
