# Generated by Django 3.0.3 on 2023-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0006_auto_20230718_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_env_path', models.CharField(default='这里修改成你 myenv 的路径', help_text='例如 H:/MyGitProject/NovelAI/UserEdition/sell_NovelAI_txt2video_web/myenv', max_length=255)),
            ],
            options={
                'verbose_name': '这里设置myenv的路径',
                'verbose_name_plural': '这里设置myenv的路径',
            },
        ),
    ]
