# Generated by Django 3.0.3 on 2023-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0008_pythonenv_whisper_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(choices=[('https://api.zhishuyun.com/chatgpt?token=', '知数云1'), ('https://api2.zhishuyun.com/chatgpt?token=', '知数云2'), ('https://openai.com', 'OPENAI'), ('https://api.closeai-proxy.xyz', 'CloseAI'), ('https://fanyi.baidu.com', '【Free】百度直译'), ('https://api.anthropic.com', '【Pay】Claude')], help_text='选择翻译API，支持【知数云，OpenAI,CloseAI,Claude,Slack,百度直译】', max_length=255, verbose_name='API-Url')),
                ('max_retries', models.IntegerField(default=999, help_text='默认999即自动重试999次', verbose_name='访问重试次数')),
                ('retry_time', models.IntegerField(default=0, help_text='默认0为不强制重拾,具体数值即n秒自动重试', verbose_name='访问重试时间（秒）')),
                ('questions_gpt', models.CharField(choices=[('自定义组合', '自定义组合'), ('关键词描述权重版1', '关键词描述权重版1'), ('关键词描述权重版2', '关键词描述权重版2'), ('关键词描述漫画导演版', '关键词描述漫画导演版'), ('关键词描述故事叙述版', '关键词描述故事叙述版'), ('语义切割短句版', '语义切割短句版'), ('语义切割长句版', '语义切割长句版'), ('都市情景叙述版', '都市情景叙述版'), ('【电影解说改写】', '【电影解说改写】')], help_text='不支持自定义，组合信息访问：https://datayang.blog.csdn.net/article/details/130909870', max_length=10, verbose_name='提问组合')),
                ('questions_txt_1', models.TextField(default='-', help_text='提问组合选择【自定义组合】生效，格式为【前半+你的描述+后半】', verbose_name='自定义组合前半部分')),
                ('questions_txt_2', models.TextField(default='-', help_text='提问组合选择【自定义组合】生效，格式为【前半+你的描述+后半】', verbose_name='自定义组合后半部分')),
            ],
            options={
                'verbose_name': 'ChatGPT-API管理',
                'verbose_name_plural': 'ChatGPT-API管理',
            },
        ),
    ]
