# Generated by Django 3.0.3 on 2023-08-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0009_chatgpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_host', models.CharField(default='eastus.api.cognitive.microsoft.com', help_text='不懂不要乱动', max_length=100, verbose_name='TTS服务地址')),
                ('speech_name', models.CharField(choices=[('zh-CN, XiaoxiaoNeural', '晓晓 （女）'), ('zh-CN, YunxiNeural', '云希 （男）'), ('zh-CN, YunjianNeural', '云建 （男）'), ('zh-CN, XiaoyiNeural', '晓毅 （女）'), ('zh-CN, YunyangNeural', '云扬 （男）'), ('zh-CN, XiaochenNeural', '晓晨 （女）'), ('zh-CN, XiaohanNeural', '晓韩 （女）'), ('zh-CN, XiaomengNeural', '晓孟 （女）'), ('zh-CN, XiaomoNeural', '晓墨 （女）'), ('zh-CN, XiaoqiuNeural', '晓邱 （女）'), ('zh-CN, XiaoruiNeural', '晓睿 （女）'), ('zh-CN, XiaoshuangNeural', '晓双 （女性、儿童）'), ('zh-CN, XiaoxuanNeural', '晓萱 （女）'), ('zh-CN, XiaoyanNeural', '晓研 （女）'), ('zh-CN, XiaoyouNeural', '晓悠 （女性、儿童）'), ('zh-CN, XiaozhenNeural', '晓珍 （女）'), ('zh-CN, YunfengNeural', '云风 （男）'), ('zh-CN, YunhaoNeural', '云浩 （男）'), ('zh-CN, YunxiaNeural', '云霞 （男）'), ('zh-CN, YunyeNeural', '云叶 （男）'), ('zh-CN, YunzeNeural', '云泽 （男）')], max_length=255, verbose_name='配音发音人')),
                ('speech_style', models.CharField(choices=[('advertisement_upbeat', '兴奋'), ('affectionate', '高音调'), ('angry', '厌恶'), ('customerservice', '热情'), ('calm', '冷静'), ('chat', '轻松'), ('cheerful', '愉快'), ('depressed', '忧郁'), ('disgruntled', '轻蔑'), ('documentary-narration', '纪录片'), ('embarrassed', '犹豫'), ('empathetic', '关切'), ('envious', '钦佩'), ('excited', '希望'), ('fearful', '紧张'), ('friendly', '愉悦'), ('hopeful', '温和'), ('lyrical', '优美'), ('narration-professional', '朗读'), ('narration-relaxed', '阅读'), ('newscast', '新闻'), ('newscast-casual', '通用'), ('newscast-formal', '权威'), ('poetry-reading', '快节奏'), ('sad', '悲伤'), ('serious', '严肃'), ('shouting', '高声'), ('sports_commentary', '赛事'), ('sports_commentary_excited', '精彩'), ('whispering', '柔和'), ('terrified', '疯狂'), ('unfriendly', '无情')], max_length=255, verbose_name='配音语气')),
                ('speech_role', models.CharField(choices=[('Girl', '女孩'), ('Boy', '男孩'), ('YoungAdultFemale', '年轻的成年女性'), ('YoungAdultMale', '年轻的成年男性'), ('OlderAdultFemale', '年长的成年女性'), ('OlderAdultMale', '年长的成年男性'), ('SeniorFemale', '年老女性'), ('SeniorMale', '年老男性')], max_length=255, verbose_name='配音年龄段')),
                ('speech_gender', models.CharField(choices=[('Male', '男'), ('Female', '女')], max_length=20, verbose_name='配音性别')),
                ('audio_rate', models.FloatField(help_text='填1.4即原始语速加速*1.4', verbose_name='语速倍数')),
            ],
            options={
                'verbose_name': 'TTS API管理',
                'verbose_name_plural': 'TTS API管理',
            },
        ),
        migrations.AlterModelOptions(
            name='pythonenv',
            options={'verbose_name': '设置myenv的路径', 'verbose_name_plural': '设置myenv的路径'},
        ),
        migrations.AlterField(
            model_name='chatgpt',
            name='questions_gpt',
            field=models.CharField(choices=[('自定义组合', '自定义组合'), ('关键词描述权重版1', '【镜头分镜】关键词描述权重版1'), ('关键词描述权重版2', '【镜头分镜】关键词描述权重版2'), ('关键词描述漫画导演版', '【镜头分镜】关键词描述漫画导演版'), ('关键词描述故事叙述版', '【镜头分镜】关键词描述故事叙述版'), ('语义切割短句版', '【镜头分镜】语义切割短句版'), ('语义切割长句版', '【镜头分镜】语义切割长句版'), ('都市情景叙述版', '【镜头分镜】都市情景叙述版'), ('【电影解说改写】', '【电影解说】文案改写')], help_text='不支持自定义，组合信息访问：https://datayang.blog.csdn.net/article/details/130909870', max_length=10, verbose_name='提问组合'),
        ),
    ]
