# Generated by Django 3.0.3 on 2023-08-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0010_auto_20230822_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TTS',
        ),
        migrations.AlterModelOptions(
            name='tts_microsoft',
            options={'verbose_name': '微软 文本转语音', 'verbose_name_plural': '微软 文本转语音'},
        ),
        migrations.AddField(
            model_name='tts_microsoft',
            name='access_token_host',
            field=models.CharField(default='eastus.api.cognitive.microsoft.com', help_text='不懂不要乱动', max_length=100, verbose_name='TTS服务地址'),
        ),
        migrations.AddField(
            model_name='tts_microsoft',
            name='audio_rate',
            field=models.FloatField(default='1.2', help_text='填1.4即原始语速加速*1.4', verbose_name='语速倍数'),
        ),
        migrations.AddField(
            model_name='tts_microsoft',
            name='speech_gender',
            field=models.CharField(choices=[('Male', '男'), ('Female', '女')], default='Male', max_length=20, verbose_name='配音性别'),
        ),
        migrations.AddField(
            model_name='tts_microsoft',
            name='speech_name',
            field=models.CharField(choices=[('zh-CN, XiaoxiaoNeural', '晓晓 （女）'), ('zh-CN, YunxiNeural', '云希 （男）'), ('zh-CN, YunjianNeural', '云建 （男）'), ('zh-CN, XiaoyiNeural', '晓毅 （女）'), ('zh-CN, YunyangNeural', '云扬 （男）'), ('zh-CN, XiaochenNeural', '晓晨 （女）'), ('zh-CN, XiaohanNeural', '晓韩 （女）'), ('zh-CN, XiaomengNeural', '晓孟 （女）'), ('zh-CN, XiaomoNeural', '晓墨 （女）'), ('zh-CN, XiaoqiuNeural', '晓邱 （女）'), ('zh-CN, XiaoruiNeural', '晓睿 （女）'), ('zh-CN, XiaoshuangNeural', '晓双 （女性、儿童）'), ('zh-CN, XiaoxuanNeural', '晓萱 （女）'), ('zh-CN, XiaoyanNeural', '晓研 （女）'), ('zh-CN, XiaoyouNeural', '晓悠 （女性、儿童）'), ('zh-CN, XiaozhenNeural', '晓珍 （女）'), ('zh-CN, YunfengNeural', '云风 （男）'), ('zh-CN, YunhaoNeural', '云浩 （男）'), ('zh-CN, YunxiaNeural', '云霞 （男）'), ('zh-CN, YunyeNeural', '云叶 （男）'), ('zh-CN, YunzeNeural', '云泽 （男）')], default='zh-CN, YunxiNeural', max_length=255, verbose_name='配音发音人'),
        ),
        migrations.AddField(
            model_name='tts_microsoft',
            name='speech_role',
            field=models.CharField(choices=[('Girl', '女孩'), ('Boy', '男孩'), ('YoungAdultFemale', '年轻的成年女性'), ('YoungAdultMale', '年轻的成年男性'), ('OlderAdultFemale', '年长的成年女性'), ('OlderAdultMale', '年长的成年男性'), ('SeniorFemale', '年老女性'), ('SeniorMale', '年老男性')], default='Boy', max_length=255, verbose_name='配音年龄段'),
        ),
        migrations.AddField(
            model_name='tts_microsoft',
            name='speech_style',
            field=models.CharField(choices=[('advertisement_upbeat', '兴奋'), ('affectionate', '高音调'), ('angry', '厌恶'), ('customerservice', '热情'), ('calm', '冷静'), ('chat', '轻松'), ('cheerful', '愉快'), ('depressed', '忧郁'), ('disgruntled', '轻蔑'), ('documentary-narration', '纪录片'), ('embarrassed', '犹豫'), ('empathetic', '关切'), ('envious', '钦佩'), ('excited', '希望'), ('fearful', '紧张'), ('friendly', '愉悦'), ('hopeful', '温和'), ('lyrical', '优美'), ('narration-professional', '朗读'), ('narration-relaxed', '阅读'), ('newscast', '新闻'), ('newscast-casual', '通用'), ('newscast-formal', '权威'), ('poetry-reading', '快节奏'), ('sad', '悲伤'), ('serious', '严肃'), ('shouting', '高声'), ('sports_commentary', '赛事'), ('sports_commentary_excited', '精彩'), ('whispering', '柔和'), ('terrified', '疯狂'), ('unfriendly', '无情')], default='friendly', max_length=255, verbose_name='配音语气'),
        ),
    ]
