# Generated by Django 3.0.3 on 2023-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0011_auto_20230822_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tts_microsoft',
            name='api_key',
            field=models.CharField(blank=True, help_text='注册地址：https://azure.microsoft.com/zh-cn/products/cognitive-services/text-to-speech/', max_length=100, null=True, verbose_name='API秘钥'),
        ),
    ]
