# Generated by Django 3.0.3 on 2023-08-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0013_auto_20230822_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stablediffusion',
            name='moviepy_factor',
        ),
        migrations.AlterField(
            model_name='stablediffusion',
            name='adetailer',
            field=models.CharField(choices=[('true', '开启面部修复'), ('false', '关闭面部修复')], default='false', help_text='默认关闭，ADetailer开启需要有对应插件，具体查看使用文档', max_length=10, verbose_name='ADetailer修复'),
        ),
        migrations.AlterField(
            model_name='stablediffusion',
            name='enable_hr',
            field=models.CharField(choices=[('true', '开启图像高清修复'), ('false', '关闭图像高清修复')], default='true', help_text='默认开启高清修复', max_length=30, verbose_name='高清修复'),
        ),
        migrations.AlterField(
            model_name='stablediffusion',
            name='hr_upscaler',
            field=models.CharField(choices=[('R-ESRGAN 4x+ Anime6B', 'R-ESRGAN 4x+ Anime6B'), ('R-ESRGAN 4x+', 'R-ESRGAN 4x+'), ('ESRGAN_4x', 'ESRGAN_4x')], default='R-ESRGAN 4x+ Anime6B', max_length=100, verbose_name='高清修复方法'),
        ),
        migrations.AlterField(
            model_name='stablediffusion',
            name='restore_faces',
            field=models.CharField(choices=[('true', '开启面部修复'), ('false', '关闭面部修复')], default='true', help_text='默认开启', max_length=10, verbose_name='面部修复'),
        ),
        migrations.AlterField(
            model_name='stablediffusion',
            name='sd_sampler',
            field=models.CharField(choices=[('Euler a', 'Euler a'), ('Euler', 'Euler'), ('DPM++ 2S a Karras', 'DPM++ 2S a Karras'), ('DPM++ 2M Karras', 'DPM++ 2M Karras'), ('DPM++ SDE Karras', 'DPM++ SDE Karras'), ('UniPC', 'UniPC')], default='Euler a', max_length=100, verbose_name='图片采样方法'),
        ),
    ]
