# Generated by Django 3.0.3 on 2023-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0014_auto_20230822_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='JianYing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='直接复制你的项目路径，例如 H:\\debug_NovelAI_txt2video', max_length=100, verbose_name='剪影等配置路径')),
                ('image_speed', models.IntegerField(default=50, help_text='1-100,100表示整张图描述时间内全部移动完成，一般选择50即可', verbose_name='关键帧移动速度')),
                ('keyframe_direction', models.CharField(choices=[('四方向', '四方向'), ('八方向', '八方向'), ('上下方向', '上下方向'), ('左右方向', '左右方向')], default='四方向', help_text='自行选择', max_length=100, verbose_name='关键帧方向')),
            ],
            options={
                'verbose_name': '【剪映】配置，只能有一条记录',
                'verbose_name_plural': '【剪映】配置，只能有一条记录',
            },
        ),
        migrations.AlterModelOptions(
            name='stablediffusion',
            options={'verbose_name': '【SD】参数设置，只能有一条记录', 'verbose_name_plural': '【SD】参数设置，只能有一条记录'},
        ),
    ]
