# Generated by Django 3.0.3 on 2023-08-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data2', '0002_auto_20230809_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietask',
            name='cn_name',
            field=models.CharField(help_text='最后生成 MovieProcess/result 文件夹下找对应的内容', max_length=50, verbose_name='视频中文名'),
        ),
        migrations.AlterField(
            model_name='movietask',
            name='en_name',
            field=models.CharField(help_text='请将处理好的视频仍在 MovieProcess/base 文件夹下，不能有中文', max_length=50, verbose_name='视频英文名'),
        ),
    ]
