# Generated by Django 3.0.3 on 2023-08-08 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBaseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fps', models.IntegerField(default=25, help_text='范围 20 到 120 之间', validators=[django.core.validators.MinValueValidator(20, message='帧率不能低于20'), django.core.validators.MaxValueValidator(120, message='帧率不能高于120')], verbose_name='通用帧率')),
                ('brightness_num', models.FloatField(default=0, help_text='范围 -1 到 1 之间', validators=[django.core.validators.MinValueValidator(-1.0, message='亮度不能低于-1.0'), django.core.validators.MaxValueValidator(1.0, message='亮度不能高于1.0')], verbose_name='通用亮度')),
                ('saturation_num', models.FloatField(default=0.0, help_text='范围 0 到 3.0 之间', validators=[django.core.validators.MinValueValidator(0, message='亮度不能低于0'), django.core.validators.MaxValueValidator(3, message='亮度不能高于3.0')], verbose_name='通用饱和度')),
                ('contrast_num', models.FloatField(default=1.0, help_text='范围 -2 到 2 之间', validators=[django.core.validators.MinValueValidator(-2.0, message='亮度不能低于-2.0'), django.core.validators.MaxValueValidator(2.0, message='亮度不能高于2.0')], verbose_name='通用对比度度')),
                ('unsharp_l_msize_x', models.IntegerField(default=5, help_text='范围 3 到 10 之间', validators=[django.core.validators.MinValueValidator(3, message='亮度不能低于3'), django.core.validators.MaxValueValidator(10, message='亮度不能高于10')], verbose_name='X方向的锐化半径')),
                ('unsharp_l_msize_y', models.IntegerField(default=5, help_text='范围 3 到 10 之间', validators=[django.core.validators.MinValueValidator(3, message='亮度不能低于3'), django.core.validators.MaxValueValidator(10, message='亮度不能高于10')], verbose_name='Y方向的锐化半径')),
                ('unsharp_l_amount', models.IntegerField(default=5, help_text='范围 -2 到 5 之间', validators=[django.core.validators.MinValueValidator(-2, message='亮度不能低于-2'), django.core.validators.MaxValueValidator(5, message='亮度不能高于5')], verbose_name='锐化强度')),
                ('hqdn3d_luma_spatial', models.IntegerField(default=1.5, help_text='较大的值会增加降噪效果', verbose_name='空间降噪强度')),
                ('hqdn3d_chroma_spatia', models.IntegerField(default=1.5, help_text='较大的值会增加降噪效果', verbose_name='色度通道降噪强度')),
                ('hqdn3d_luma_tmp', models.IntegerField(default=6, help_text='较大的值会增加降噪效果', verbose_name='时间降噪强度')),
                ('hqdn3d_chroma_tmp', models.IntegerField(default=6, help_text='较大的值会增加降噪效果', verbose_name='色度时间降噪强度')),
                ('scale', models.CharField(choices=[('480P', '480P'), ('720P', '720P'), ('1080P', '1080P'), ('横竖互换', '横竖互换')], default='', max_length=20, verbose_name='视频分辨率')),
                ('transpose', models.CharField(choices=[('逆时针旋转90度', '逆时针旋转90度'), ('顺时针旋转90度', '顺时针旋转90度'), ('水平旋转', '水平旋转'), ('垂直旋转', '垂直旋转'), ('不操作', '不操作')], default='', max_length=20, verbose_name='视频旋转')),
                ('frame_set', models.CharField(choices=[('设置抽帧', '设置抽帧'), ('不设置抽帧', '不设置抽帧')], default='', max_length=20, verbose_name='视频旋转')),
                ('frame_set_max', models.IntegerField(default=20, help_text='抽帧在【下限-上限】之间随机抽帧', verbose_name='随机抽帧下限')),
                ('frame_set_min', models.IntegerField(default=30, help_text='抽帧在【下限-上限】之间随机抽帧', verbose_name='随机抽帧上限')),
            ],
        ),
    ]
