# Generated by Django 3.0.3 on 2023-08-08 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data1', '0003_auto_20230808_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fps', models.IntegerField(default=30, help_text='范围 20 到 120 之间', validators=[django.core.validators.MinValueValidator(20, message='帧率不能低于20'), django.core.validators.MaxValueValidator(120, message='帧率不能高于120')], verbose_name='通用帧率')),
                ('frame_insert_num', models.IntegerField(default=25, help_text='推荐 20 到 30 之间', verbose_name='间隔插入帧数')),
                ('blend_num', models.FloatField(default=0.01, help_text='0 到 1 之间，0表示全透明，1表示原图', verbose_name='帧透明度')),
                ('add_min_count', models.IntegerField(default=20, help_text='抽帧在【下限-上限】之间随机补帧', verbose_name='随机抽帧下限')),
                ('add_max_count', models.IntegerField(default=30, help_text='抽帧在【下限-上限】之间随机补帧', verbose_name='随机抽帧上限')),
            ],
            options={
                'verbose_name': '插帧/补帧设置',
                'verbose_name_plural': '插帧/补帧设置',
            },
        ),
    ]
