# Generated by Django 3.0.3 on 2023-08-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data1', '0004_frameprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobasesetting',
            name='scale_x',
            field=models.IntegerField(default=100, help_text='只有视频分辨率选择自定义才会生效', verbose_name='自定义分辨率宽'),
        ),
        migrations.AddField(
            model_name='videobasesetting',
            name='scale_y',
            field=models.IntegerField(default=100, help_text='只有视频分辨率选择自定义才会生效', verbose_name='自定义分辨率宽'),
        ),
        migrations.AlterField(
            model_name='videobasesetting',
            name='scale',
            field=models.CharField(choices=[('480P', '480P(横版)'), ('720P', '720P(横版)'), ('1080P', '1080P(横版)'), ('横竖互换', '横竖互换'), ('自定义', '自定义')], default='', max_length=20, verbose_name='视频分辨率'),
        ),
    ]
