# Generated by Django 3.0.3 on 2023-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data1', '0005_auto_20230809_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobasesetting',
            name='scale_x',
            field=models.IntegerField(default=100, help_text='只有视频分辨率选择自定义才会生效', verbose_name='自定义分辨率宽（宽）'),
        ),
        migrations.AlterField(
            model_name='videobasesetting',
            name='scale_y',
            field=models.IntegerField(default=100, help_text='只有视频分辨率选择自定义才会生效', verbose_name='自定义分辨率宽（高）'),
        ),
    ]
