# Generated by Django 3.0.3 on 2023-05-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_framework', models.TextField(default='-', help_text='如果没有可以不填', verbose_name='故事框架')),
                ('content', models.TextField(help_text='文章整理过之后直接复制过来接口', verbose_name='故事正文')),
                ('len_text', models.IntegerField(blank=True, verbose_name='文章字数计算')),
                ('type', models.CharField(help_text='类别相同会将所有同类文章放到此目录下', max_length=50, verbose_name='文章类别')),
                ('en_name', models.CharField(help_text='故事正文下所有的数据都会在次目录下保存', max_length=50, verbose_name='文章英文名')),
                ('cn_name', models.CharField(help_text='生成数据文件视频和docx的命名', max_length=50, verbose_name='文章中文名')),
                ('status', models.CharField(choices=[('已完成', '已完成'), ('未完成', '未完成')], help_text='批量执行时会跳过标记已完成的数据', max_length=5, verbose_name='数据状态')),
            ],
            options={
                'verbose_name': '文章任务管理',
                'verbose_name_plural': '文章任务管理',
            },
        ),
        migrations.CreateModel(
            name='TaskEach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(verbose_name='每句话的文章正文')),
                ('index', models.CharField(max_length=255, verbose_name='每句话的文章索引')),
                ('prompt', models.TextField(verbose_name='每句话的文章正面词')),
                ('negative', models.TextField(verbose_name='每句话的文章负面此')),
                ('img', models.CharField(max_length=255, verbose_name='每句话图片保存地址')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Task')),
            ],
            options={
                'verbose_name': '文章明细管理',
                'verbose_name_plural': '文章明细管理',
            },
        ),
    ]
