# Generated by Django 3.0.3 on 2023-06-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lorat_temp',
            field=models.TextField(default=1, help_text='不懂尽量不要动', verbose_name='lora 配置'),
            preserve_default=False,
        ),
    ]
