# Generated by Django 3.0.3 on 2023-06-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20230604_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lora_temp',
            field=models.TextField(blank=True, help_text='不懂尽量不要动', null=True, verbose_name='lora 配置'),
        ),
    ]
