# Generated by Django 3.0.3 on 2023-07-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0004_auto_20230604_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '文生图任务管理', 'verbose_name_plural': '文生图任务管理'},
        ),
    ]
