# Generated by Django 3.0.3 on 2023-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0006_taskeach_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content_start',
            field=models.CharField(default='', help_text='黄金5秒开头文案', max_length=200, verbose_name='开头文案'),
        ),
        migrations.AddField(
            model_name='task',
            name='content_start_json',
            field=models.TextField(default='', help_text='黄金5秒开头文案json', verbose_name='开头文案'),
        ),
    ]
